Fix/order view
M5-Developers/S7-03-Projeto-Backend---Template-2---Kenzie-Commerce- pull request #22
Opened 2023-05-09 21:02 UTC by Eliasjp

O retorno do post de Order não está chegando com os produtos

2023-05-09 21:19 UTC, gabrielgpavao requested changes
Fala Elias, beleza?
Parece que ta tudo certinho.
Só um ponto aqui pra checar:
- No arquivo de views de Orders, da linha 43-45 vi que tu declarou uma variável "teste" e depois faz um print. Se for só pra teste mesm, então apaga essa parte pfv pra gente não subir pra develop.

2023-05-10 01:01 UTC, luis-mendes-95 approved these changes

2023-05-10 01:02 UTC, luis-mendes-95 approved these changes

2023-05-10 12:01 UTC, gabrielgpavao requested changes
- No arquivo de views de Carts, apaga os comentários por gentileza, só pra gente não subir isso pra develop. Aí é só dar um push de nove que já aceito aqui.

2023-05-10 12:34 UTC, merged